package jfshub;

import java.awt.Image;
import javax.swing.ImageIcon;
import jfshub.Datos.DataCode;

/**
 *
 * @author Crhistian C
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        cargarDatos();
        propiedadesJFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelGeneral = new javax.swing.JPanel();
        txt_bienvenida = new javax.swing.JLabel();
        bInformacionGeneral = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        paneles = new javax.swing.JLayeredPane();
        panelDefault = new javax.swing.JPanel();
        txtPanelDefault = new javax.swing.JLabel();
        panelInformacion = new javax.swing.JPanel();
        txtInfo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtEdad = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        txtPais = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellido = new javax.swing.JLabel();
        labelEdad = new javax.swing.JLabel();
        labelPais = new javax.swing.JLabel();
        labelId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        panelLosJFS = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_bienvenida.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        txt_bienvenida.setText("TXT_BIENVENIDA");

        bInformacionGeneral.setText("Información general");
        bInformacionGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInformacionGeneralActionPerformed(evt);
            }
        });

        jButton2.setText("Los JFS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("DESHABILITADO");

        jButton4.setText("DESHABILITADO");

        jButton5.setText("DESHABILITADO");

        paneles.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paneles.setLayout(new java.awt.CardLayout());

        txtPanelDefault.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtPanelDefault.setText("Elige el panel que quieras editar");

        javax.swing.GroupLayout panelDefaultLayout = new javax.swing.GroupLayout(panelDefault);
        panelDefault.setLayout(panelDefaultLayout);
        panelDefaultLayout.setHorizontalGroup(
            panelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDefaultLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(txtPanelDefault)
                .addGap(136, 136, 136))
        );
        panelDefaultLayout.setVerticalGroup(
            panelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDefaultLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(txtPanelDefault)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        paneles.add(panelDefault, "card4");

        txtInfo.setFont(new java.awt.Font("Dialog", 2, 10)); // NOI18N
        txtInfo.setText("Estamos trabajando para que puedas editar tus datos desde esta pantalla *Inserte emoji sonriendo aquí*.");

        txtNombre.setText("Nombre:");

        txtApellido.setText("Apellido:");

        txtEdad.setText("Edad:");

        txtId.setText("Número de identificación:");

        txtPais.setText("Nacionalidad:");

        labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNombre.setText("NOMBRE");

        labelApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelApellido.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelApellido.setText("APELLIDO");

        labelEdad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelEdad.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEdad.setText("EDAD");

        labelPais.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPais.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPais.setText("PAIS");

        labelId.setText("ID");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        jLabel1.setText("*Inserte información importante aquí, desarrollador kbro*");
        jLabel1.setToolTipText("");

        txtCorreo.setText("Correo registrado:");

        labelCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCorreo.setText("CORREO");

        javax.swing.GroupLayout panelInformacionLayout = new javax.swing.GroupLayout(panelInformacion);
        panelInformacion.setLayout(panelInformacionLayout);
        panelInformacionLayout.setHorizontalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelId)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionLayout.createSequentialGroup()
                        .addGap(0, 49, Short.MAX_VALUE)
                        .addComponent(txtInfo)
                        .addGap(70, 70, 70))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInformacionLayout.createSequentialGroup()
                                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellido))
                                .addGap(39, 39, 39)
                                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelNombre)
                                    .addComponent(labelPais)
                                    .addComponent(labelApellido)
                                    .addComponent(labelEdad))
                                .addGap(73, 73, 73)
                                .addComponent(txtCorreo)
                                .addGap(44, 44, 44)
                                .addComponent(labelCorreo))
                            .addComponent(txtPais)
                            .addComponent(txtEdad))
                        .addContainerGap(156, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelInformacionLayout.setVerticalGroup(
            panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacionLayout.createSequentialGroup()
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido)
                            .addComponent(labelApellido)))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre)
                            .addComponent(labelNombre)
                            .addComponent(txtCorreo)
                            .addComponent(labelCorreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)))
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformacionLayout.createSequentialGroup()
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId)
                            .addComponent(labelId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panelInformacionLayout.createSequentialGroup()
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEdad)
                            .addComponent(txtEdad))
                        .addGap(43, 43, 43)
                        .addGroup(panelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPais)
                            .addComponent(labelPais))
                        .addGap(99, 99, 99)))
                .addComponent(txtInfo))
        );

        paneles.add(panelInformacion, "card2");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel2.setText("*Inserte información de relación del usuario con Los JFS*");

        javax.swing.GroupLayout panelLosJFSLayout = new javax.swing.GroupLayout(panelLosJFS);
        panelLosJFS.setLayout(panelLosJFSLayout);
        panelLosJFSLayout.setHorizontalGroup(
            panelLosJFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLosJFSLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        panelLosJFSLayout.setVerticalGroup(
            panelLosJFSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLosJFSLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel2)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        paneles.add(panelLosJFS, "card3");

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addComponent(bInformacionGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txt_bienvenida)
                .addContainerGap(676, Short.MAX_VALUE))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txt_bienvenida)
                .addGap(48, 48, 48)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bInformacionGeneral)
                        .addGap(46, 46, 46)
                        .addComponent(jButton2)
                        .addGap(52, 52, 52)
                        .addComponent(jButton3)
                        .addGap(57, 57, 57)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(47, 47, 47))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bInformacionGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInformacionGeneralActionPerformed
        panelDefault.setVisible(false);
        panelLosJFS.setVisible(false);
        panelInformacion.setVisible(true);
    }//GEN-LAST:event_bInformacionGeneralActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        panelDefault.setVisible(false);
        panelInformacion.setVisible(false);
        panelLosJFS.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInformacionGeneral;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel labelApellido;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelEdad;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPais;
    private javax.swing.JPanel panelDefault;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JPanel panelInformacion;
    private javax.swing.JPanel panelLosJFS;
    private javax.swing.JLayeredPane paneles;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtEdad;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtInfo;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPais;
    private javax.swing.JLabel txtPanelDefault;
    private javax.swing.JLabel txt_bienvenida;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos() {
        //panel Informaciôn General//
        txt_bienvenida.setText("¡Hola, " + Datos.get(DataCode.NOMBRE) + "!");
        labelId.setText(Datos.get(DataCode.ID));
        labelNombre.setText(Datos.get(DataCode.NOMBRE));
        labelApellido.setText(Datos.get(DataCode.APELLIDO));
        labelEdad.setText(Datos.get(DataCode.EDAD));
        labelPais.setText(Datos.get(DataCode.PAIS));
        labelCorreo.setText(Datos.get(DataCode.CORREO));
        //*************************//

    }

    private void propiedadesJFrame() {
        ImageIcon img = new ImageIcon(JFSHub.class.getResource("images/icono1.png"));
        setIconImage(img.getImage().getScaledInstance(14, 15, Image.SCALE_DEFAULT));
        
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("[JFS Hub] " + Datos.get(DataCode.NOMBRE));
        setVisible(true);
    }
}
